services:
  foxglove_bridge:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: foxglove_bridge
    network_mode: host          
    ipc: host                   
    environment:
      - ROS_DOMAIN_ID=0
      - RCUTILS_LOGGING_MIN_SEVERITY=INFO
      - FREQUENCY=${FREQUENCY}
      - NUM_TOPICS=${NUM_TOPICS}
    ports:
      - "8765:8765"             
